os:
    - linux
language: generic
sudo: required
dist: trusty

script:
    - swift build --configuration release
      swift test

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
